pipeline{
  agent any
  		 tools{
  		 maven 'maven-3.6.3'
  		 jdk 'jdk1.8.0_211'
  		 }
  		 stages{
  		 	stage('build'){
  		 					steps{
  		 					bat 'mvn compiler:compile'
  		 					}
  		 					post{
  		 		success {
  		 			bat "echo 'Projet compilé avec succès'"

  		 		}
  		 		failure {
  		 			bat "echo 'Erreur lors de la compilation de projet '"
  		 		}
  		 					}
  		 	}
  		 		stage('Test'){
  		 	steps {
  		 		bat 'mvn test'
  		 		}
  		 		
  		
  		 		  		 	}
  		 		  	stage('couverture') {
  		 		steps{

  		 			bat 'mvn cobertura:cobertura -Dcobertura.report.format=xml'
  		 		  	}

  		 		




  		 		}

  		 		}
 }
